### ISSUE TITLE
"panic: Decoder for serialization format 3 not implemented"

### ISSUE THREAD

**Issue by gracianipicardo** [knakk/rdf2rdf#3]
First time user of Go here, and testing this tool to convert a n-quads dataset to n-triples. Getting the following error message and not sure where to even start troubleshooting. Working on a Windows 10 and installed Go using the MSI installer. Anything I should be looking at?

Thanks!

```
C:\>rdf2rdf -in=SVDE_data\records_15639650429820.13506094280866998.nq -out=SVDE_data\records_15639650429820.13506094280866998.nt
panic: Decoder for serialization format 3 not implemented

goroutine 1 [running]:
github.com/knakk/rdf.NewTripleDecoder(0x57c3c0, 0xc000006030, 0x3, 0x55b100, 0x0)
        C:/Users/pg6498/go/src/github.com/knakk/rdf/decoder.go:65 +0x376
main.tripleToTriple(0x57c3c0, 0xc000006030, 0x57c3e0, 0xc000006038, 0x3, 0x0, 0x1, 0xc00002e360)
        C:/Users/pg6498/go/src/github.com/knakk/rdf2rdf/rdf2rdf.go:149 +0x64
main.main()
        C:/Users/pg6498/go/src/github.com/knakk/rdf2rdf/rdf2rdf.go:142 +0x645
```

**Comment by boutros** [comment]
Hi, your're quite rigt there is a bug.
For nq the QuadDecoder should be used, not TripleDecoder
https://godoc.org/github.com/knakk/rdf#QuadDecoder

I will look into it eventually, but it might be a while before I fix it.

Anyone feel free to have a go at it in the meantime. It should be trivial.
